Repository kimkyeongnam/OSS-SnakeGame, pull requests merged in 2019-05, with the labels that each got.

#11 separate functions
  main.c
Labels: Clean

#13 Declare functions of the original form
  main.c
Labels: Clean, Merge

#14 Split functions related Map
  main.c
Labels: Clean, Merge

#15 Change Constants to Magic number & Change Conditional Expressions to Fuctions
  main.c
Labels: Clean, Merge

#16 Functioning relocate food and snake
  main.c
Labels: Clean, Merge

#28 Modify Map random position error
  main.c
Labels: Bug, Improvement

#35 New/iss17_tail (꼬리 생성 기능 추가)
  main.c
Labels: Improvement, New

#39 꼬리 기능 오류 해결
  main.c
Labels: Bug, Improvement, New

#40 solve iss29 encoding error and code clean
  main.c
Labels: Bug, Clean, Merge

#41 Add Intro
  main.c
Labels: Bug, Clean, New
